# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp
#' @param N the number of samples
#' @param thin the number of between-sample random numbers
#' @return a random sample of size \code{n}
#' @examples
#' \dontrun{
#' rnC <- gibbsC(100,10)
#' par(mfrow=c(2,1));
#' plot(rnC[,1],type='l')
#' plot(rnC[,2],type='l')
#' }
#' @export
gibbsC <- function(N, thin) {
    .Call('_StatComp20048_gibbsC', PACKAGE = 'StatComp20048', N, thin)
}

#' @title A function of Fibonacci sequence using Rcpp
#' @description A function to calculate the nth term of the Fibonacci sequence
#' @param n the nth term of the Fibonacci sequence
#' @return a int number
#' @examples
#' \dontrun{
#' fib1 <- fib_cpp_1(10)
#' }
#' @export
fib_cpp_1 <- function(n) {
    .Call('_StatComp20048_fib_cpp_1', PACKAGE = 'StatComp20048', n)
}

#' @title A sum function using Rcpp
#' @description A function to calculate the sum of a vector
#' @param x the numeric vector
#' @return sum
#' @examples
#' \dontrun{
#' rnC <- sum3(1:10)
#' }
#' @export
sum3 <- function(x) {
    .Call('_StatComp20048_sum3', PACKAGE = 'StatComp20048', x)
}

